build:develop:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":latest .
    - docker push "$CI_REGISTRY_IMAGE":latest
    # - docker tag "$CI_REGISTRY_IMAGE":latest "$CI_REGISTRY_IMAGE":<id>
    # - docker push "$CI_REGISTRY_IMAGE":<id>
  only:
    - gitlab-ci

build:release:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' && $CI_COMMIT_TAG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":$CI_COMMIT_TAG .
    - docker push "$CI_REGISTRY_IMAGE":$CI_COMMIT_TAG
